### PR TITLE
Selenium-Basic-Installation-Package

### PR DESCRIPTION
**Pull request by VikasVashisth**
I have added selenium installation guide so that it would be easier for the beginners to run the Selenium projects.

### CODE REVIEW

**Review by Manas-kashyap — APPROVED** [review]

**Review by Manas-kashyap — CHANGES_REQUESTED** [review]
I dont think we need one line installation scripts for the same and belive we have already installation scripts of these.

**Comment by VikasVashisth** [comment]
> I dont think we need one line installation scripts for the same and belive we have already installation scripts of these.

**Comment by VikasVashisth** [comment]
> I dont think we need one line installation scripts for the same and belive we have already installation scripts of these.

I thought to add one small package for all the requirements to run the selenium and also i don't find the java or intellij installation scripts.

**Comment by VikasVashisth** [comment]
> I thought to add one small package for all the requirements to run the selenium and also i don't find the java or intellij installation scripts.

I thought to add one small package for all the requirements to run the selenium and also i don't find the java or intellij installation scripts.

**Comment by VikasVashisth** [comment]
> > I thought to add one small package for all the requirements to run the selenium and also i don't find the java or intellij installation scripts.
> 
> .

**Pull request closed without merging**
